# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-30 10:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Studentsprofile',
        ),
    ]
