# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsprofile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='profile_photo'),
        ),
    ]
