# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-23 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20160530_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsprofile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='ProfileImage'),
        ),
    ]
