# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-26 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentsprofile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsprofile',
            name='photo',
        ),
    ]
