# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-26 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametry', '0008_groupofstudents_lead'),
        ('students', '0004_remove_studentsprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsprofile',
            name='group',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='parametry.Groupofstudents'),
            preserve_default=False,
        ),
    ]
