# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametry', '0008_groupofstudents_lead'),
        ('students', '0004_remove_studentsprofile_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsprofile',
            old_name='dait_of_birth',
            new_name='date_of_birth',
        ),
        migrations.AddField(
            model_name='studentsprofile',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parametry.Groupofstudents'),
            preserve_default=False,
        ),
    ]
