# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20160626_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsprofile',
            name='date_of_birth',
            field=models.DateField(verbose_name='\u0414\u0430\u0442\u0430 \u043d\u0430\u0440\u043e\u0434\u0436\u0435\u043d\u043d\u044f'),
        ),
        migrations.AlterField(
            model_name='studentsprofile',
            name='firstname',
            field=models.CharField(max_length=50, verbose_name='\u0406\u043c\u044f'),
        ),
        migrations.AlterField(
            model_name='studentsprofile',
            name='lastname',
            field=models.CharField(max_length=50, verbose_name='\u041f\u0440\u0438\u0437\u0432\u0456\u0449\u0435'),
        ),
        migrations.AlterField(
            model_name='studentsprofile',
            name='middlename',
            field=models.CharField(max_length=50, verbose_name='\u041f\u043e \u0431\u0430\u0442\u044c\u043a\u043e\u0432\u0456'),
        ),
        migrations.AlterField(
            model_name='studentsprofile',
            name='students_ticket',
            field=models.IntegerField(default=0, verbose_name='\u2116 \u0411\u0456\u043b\u0435\u0442\u0443'),
        ),
    ]
