# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20160627_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsprofile',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametry.Groupofstudents', verbose_name='\u0413\u0440\u0443\u043f\u0430'),
        ),
    ]
