# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groupofstudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='\u0413\u0440\u0443\u043f\u0438')),
            ],
            options={
                'verbose_name_plural': 'Groupofstudents',
            },
        ),
    ]
