# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametry', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupofstudents',
            name='lead',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.Studentsprofile', verbose_name='\u0421\u0442\u0430\u0440\u043e\u0441\u0442\u0430'),
        ),
    ]
