# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-07 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametry', '0002_auto_20160530_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupofstudents',
            name='chief',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
