# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-07 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametry', '0003_groupofstudents_chief'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupofstudents',
            name='chief',
        ),
    ]
