# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-23 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametry', '0004_remove_groupofstudents_chief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupofstudents',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='\u0413\u0440\u0443\u043f\u0438'),
        ),
    ]
