# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-23 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametry', '0005_auto_20160623_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupofstudents',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
