# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametry', '0007_auto_20160626_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupofstudents',
            name='lead',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
